### ISSUE TITLE
pfQuest

### ISSUE THREAD

**Issue by Armzeruel** [endless-addons/.github#2]
**Addon name:**
pfQuest

**Addon Link (optional):**
https://github.com/shagu/pfQuest/releases/latest/download/pfQuest-full-tbc.zip

**Reason for Request (optional):**
Only addon that show quests that wasnt picked before,making questing more fun and efficient. Questhelper lacks that functional.
**Additional Information (optional):**

**Comment by Jerrythemagicdog** [comment]
Thanks for the suggestion, added to library.
