### ISSUE TITLE
Xperl

### ISSUE THREAD

**Issue by Armzeruel** [endless-addons/.github#3]
**Addon Name:**
Xperl

**Addon Link (optional):**
https://legacy-wow.com/wotlk-addons/xperl-unitframes/Download

**Reason for Request (optional):**
Popular frames addon. They are like favourite tableware,or car seats, necessary for comfort.

**Additional Information (optional):**

**Comment by Jerrythemagicdog** [comment]
Thanks for the suggestion, added to the library.
