### ISSUE TITLE
Raid/party interface

### ISSUE THREAD

**Issue by Djenery** [endless-addons/.github#7]
**Addon Name:**
CompactRaidFrame

**Addon Link (optional):**
https://github.com/RomanSpector/CompactRaidFrame

**Reason for Request (optional):**
The most comfortable raid/party interface since cata till nowa days on official servers.

**Additional Information (optional):**
It works fine on your server but maybe you can add it to launcher so more people can start use it

**Comment by Jerrythemagicdog** [comment]
Thanks for the suggestion, we've added it to the launcher's AddOn library.
